# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180823_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafemeals',
            options={'verbose_name': 'Cafe product', 'verbose_name_plural': 'Cafe products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
    ]
