# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181016_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
