# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0004_auto_20181207_1956'),
        ('products', '0013_auto_20181206_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='modifiers.ModifierCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product modifier',
                'verbose_name_plural': 'Product modifiers',
            },
        ),
    ]
