# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 16:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productmodifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
