# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181207_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='is_active',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='active',
            new_name='available',
        ),
    ]
