# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181210_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='title',
            new_name='name',
        ),
    ]
