# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
