# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_point'),
        ('orders', '0005_auto_20180714_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Cafe'),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
