# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180804_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pre_order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
