# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180804_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pre_order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
