# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('ready', 'Ready')], default='new', max_length=60),
        ),
    ]
