# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20181026_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('ready', 'Ready'), ('reject', 'Reject')], default='new', max_length=60),
        ),
    ]
