# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0008_auto_20181213_1633'),
        ('orders', '0020_cartmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodifier',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_modifier_items', to='modifiers.Modifier'),
        ),
        migrations.AlterField(
            model_name='cartmodifier',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order_items', to='orders.Order'),
        ),
    ]
