# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_cartmodifier_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodifier',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.Cart'),
        ),
    ]
