# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20180702_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
