# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 12:36
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20180712_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='postal_code',
            field=localflavor.us.models.USPostalCodeField(max_length=2, null=True),
        ),
    ]
