# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_cafe_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='postal_code',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
