# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20180712_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeLikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cafe')),
                ('like_dislike_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike_cafe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
