# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_album'),
        ('users', '0075_cafelikedislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='users.Cafe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_meals', to='products.Product')),
            ],
        ),
    ]
