# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_cafemeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafemeals',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='cafemeals',
            name='product',
        ),
        migrations.DeleteModel(
            name='CafeMeals',
        ),
    ]
