# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
