# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Cafe'),
        ),
        migrations.AlterField(
            model_name='point',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
