# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180811_1452'),
        ('users', '0082_auto_20180804_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='order',
        ),
        migrations.AddField(
            model_name='point',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
