# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_transaction'),
        ('users', '0083_auto_20180816_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='product',
        ),
        migrations.AddField(
            model_name='point',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
