# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20180825_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL),
        ),
    ]
