# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_pointexchanging_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointexchanging',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_product', to='users.Cafe'),
        ),
    ]
