# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 12:01
from __future__ import unicode_literals

from django.db import migrations
import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20180830_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOwner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
