# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180823_1709'),
        ('users', '0092_auto_20180904_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(blank=True, max_length=120, null=True)),
                ('expiration_days', models.IntegerField(blank=True, null=True)),
                ('show_reviews', models.BooleanField(default=True)),
                ('exchangeable_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
