# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_cafegeneralsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointexchanging',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exchanger', to=settings.AUTH_USER_MODEL),
        ),
    ]
