# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_auto_20180906_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafegeneralsettings',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
