# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_cafegeneralsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafegeneralsettings',
            name='exchangeable_point',
            field=models.IntegerField(default=10),
        ),
    ]
