# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_cafegeneralsettings_exchangeable_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafegeneralsettings',
            name='expiration_days',
            field=models.IntegerField(default=30),
        ),
    ]
