# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20180910_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointexchanging',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('redeemed', 'Redeemed')], default='valid', max_length=60),
        ),
    ]
