# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_pointexchanging_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafegeneralsettings',
            options={'verbose_name': 'Cafe general setting', 'verbose_name_plural': 'Cafe general settings'},
        ),
    ]
