# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20180925_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inviter',
        ),
        migrations.AddField(
            model_name='user',
            name='user_referral_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
