# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20180925_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_referral_code',
            new_name='inviter_referral_code',
        ),
    ]
