# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_auto_20180925_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='cafe_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
