# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_point_cafe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.Cafe'),
        ),
    ]
