# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_remove_cafe_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='point',
            name='order',
        ),
    ]
