# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_auto_20181006_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointExchanging',
            new_name='FreeItem',
        ),
    ]
