# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_auto_20181006_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='cafe_owner',
        ),
        migrations.AddField(
            model_name='point',
            name='root_cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CafeGeneralSettings'),
        ),
    ]
