# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_auto_20181006_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
