# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_auto_20181006_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafelikedislike',
            old_name='like_dislike_user',
            new_name='user',
        ),
    ]
