# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_auto_20181012_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
