# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_socialprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafegeneralsettings',
            name='exchangeable_product',
        ),
    ]
