# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_image'),
        ('users', '0118_remove_cafegeneralsettings_exchangeable_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafegeneralsettings',
            name='exchangeable_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
