# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_cafegeneralsettings_exchangeable_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='notifications/'),
        ),
    ]
