# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_auto_20181204_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafegeneralsettings',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='cafe',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
