# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_auto_20181213_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
