# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0003_cafemeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemeals',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_cafes', to='users.Cafe'),
        ),
        migrations.AlterField(
            model_name='cafemeals',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_modifiers', to='modifiers.ModifierCategory'),
        ),
    ]
