# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0004_auto_20181207_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeMeals',
            new_name='CafeModifiers',
        ),
    ]
