# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 16:17
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modifiers', '0005_auto_20181207_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifier',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='modifiercategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='modifiercategory',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modifier',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
