# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0006_auto_20181207_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifier',
            old_name='active',
            new_name='available',
        ),
        migrations.AddField(
            model_name='modifiercategory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
