# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modifiers', '0007_auto_20181210_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafemodifiers',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='cafemodifiers',
            name='modifier',
        ),
        migrations.DeleteModel(
            name='CafeModifiers',
        ),
    ]
