# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0015_auto_20180911_1350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=254)),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('holder_name', models.CharField(max_length=254)),
                ('payment_type', models.CharField(max_length=254)),
                ('payment_time', models.DateTimeField()),
                ('status', models.CharField(default='in_process', max_length=60, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
