# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_stripetransaction_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripetransaction',
            name='payment_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
